# Generated by Django 4.2.5 on 2023-10-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_images'),
        ),
    ]
